"""empty message

Revision ID: 06a09972b81e
Revises: acf98e0b7cac
Create Date: 2020-07-28 18:56:02.013337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a09972b81e'
down_revision = 'acf98e0b7cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enterprise', 'is_admin')
    # ### end Alembic commands ###
