"""empty message

Revision ID: 0950e78e5951
Revises: acf98e0b7cac
Create Date: 2020-07-21 12:37:27.247853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0950e78e5951'
down_revision = 'acf98e0b7cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('date', table_name='schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('date', 'schedule', ['date'], unique=True)
    # ### end Alembic commands ###
