"""empty message

Revision ID: 65e6aa559668
Revises: 16fcaca422ae
Create Date: 2020-07-08 16:48:08.958016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65e6aa559668'
down_revision = '16fcaca422ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('name', sa.String(length=250), nullable=False))
    op.drop_column('spacetype', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spacetype', sa.Column('name', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('space', 'name')
    # ### end Alembic commands ###
