"""empty message

Revision ID: 7f0218e128db
Revises: b141665911e4
Create Date: 2020-07-13 16:21:12.106672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0218e128db'
down_revision = 'b141665911e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'schedule', ['date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='unique')
    # ### end Alembic commands ###
