"""empty message

Revision ID: 8790de232933
Revises: 057c09c024eb
Create Date: 2020-08-12 15:55:08.953643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8790de232933'
down_revision = '057c09c024eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('description', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'description')
    # ### end Alembic commands ###
