"""empty message

Revision ID: 907df834e013
Revises: e1eec8e512b6
Create Date: 2020-07-26 08:59:31.144736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '907df834e013'
down_revision = 'e1eec8e512b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('current_hours', sa.Integer(), nullable=False))
    op.drop_column('enterprise', 'tot_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('tot_hours', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('enterprise', 'current_hours')
    # ### end Alembic commands ###
