"""empty message

Revision ID: e1eec8e512b6
Revises: 0950e78e5951
Create Date: 2020-07-23 07:57:14.207522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1eec8e512b6'
down_revision = '0950e78e5951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'schedule', ['space_id', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='unique')
    # ### end Alembic commands ###
